### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by fhemberger**

### CODE REVIEW

**Comment by dictvm** [comment]
The colors no longer match because the background contained gradients that are gone in your SVG.  Can you add the gradients to SVG or is that too complex?

**Comment by fhemberger** [comment]
Took the background from the .ai file and just fixed some of the polygons … I'll look into it.

**Comment by fhemberger** [comment]
Hmm, I see what you mean, but I don't have a recent Illustrator version, so I can't extract the additional coloring layer for the SVG. Maybe Christina can export a better version. Afterwards the file should be optimized with [svgo](https://github.com/svg/svgo).

**Comment by fhemberger** [comment]
If the background image issue is blocking the merge … could you at least consider the other commits?

**Comment by dictvm** [comment]
I have to admit that I'm not quite sure how to do that. Of course I'll accept all other commits. I'll get back to you during the weekend.

**Comment by dictvm** [comment]
I think I cherry-picked all commits and merged them. So there's only the SVG left.

**Comment by fhemberger** [comment]
@dictvm LGTM! :+1: 
Have you talked to Christina about an SVG export of the background from Illustrator yet?

**Comment by fhemberger** [comment]
Closing this for now. Maybe we still can get an SVG background in the future …

**Pull request closed without merging**
